### ISSUE TITLE
Exe version for Win11 Pro

### ISSUE THREAD

**Issue by Valsodar15** [atomofiron/img2fbm#1]
Under 64 bit Windows 11 Pro aplication img2fbm-win-x86_64.exe DONT WORK, I seen just som short flash on the screen and thats all.

**Comment by atomofiron** [comment]
friend, look the demo video and drag&drop the .exe to terminal)

**Comment by Valsodar15** [comment]
Terminal isn't opening like in video -_-

ut 12. 11. 2024 o 10:01 Jaroslav Nesterov ***@***.***>
napísal(a):

**Comment by Valsodar15** [comment]
OK, Thats process weirdly Works, but without UI. Everyone with less skil
with programming would not understand how to use it.

st 13. 11. 2024 o 18:15 Valsodar ***@***.***> napísal(a):

**Comment by atomofiron** [comment]
> Everyone with less skil with programming would not understand how to use it.

if someone buy a flipper zero, he should have minimal competence in this

**Comment by Valsodar15** [comment]
Just unfinished programing job, friendly UI is norm, nowdays.

Dňa pi 15. 11. 2024, 7:24 Jaroslav Nesterov ***@***.***>
napísal(a):
